<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>text.flag-txt</string>
    <key>fileTypes</key>
    <array>
      <string>txt</string>
    </array>
    <key>foldingStartMarker</key>
    <string/>
    <key>foldingStopMarker</key>
    <string/>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.line.flag-txt</string>
        <key>match</key>
        <string>^!!!\s*(.+)$</string>
      </dict>
      <dict>
        <key>name</key>
        <string>markup.bold.flag-txt</string>
        <key>match</key>
        <string>【.+?】</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.flag-txt</string>
        <key>match</key>
        <string>^(###|#[程框項表習]|#圖\(.+?\))</string>
      </dict>
      <dict>
        <key>name</key>
        <string>support.function.flag-txt</string>
        <key>match</key>
        <string>^(第\s*\d+\s*章.+$|([\d+]|[A-Z]+)\-\d+(.+)$|\[.+\]$|&lt;&lt;.+&gt;&gt;)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.double.flag-txt</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.flag-txt</string>
            <key>match</key>
            <string>\.</string>
          </dict>
        </array>
      </dict>
    </array>
  </dict>
</plist>